#dev 开发环境
#pro 生产环境
#阿里邮箱
#spring:
#  mail:
#    host: smtpdm.aliyun.com
#    username: fund@layku.cn
#    password: fsYl2HGJ5d6B3
#    properties:
#      mail:
#        smtp:
#          auth: true
#          starttls:
#            enable: true
#            required: true


spring:
  #QQ Mail
  mail:
    host: smtp.qq.com
    username: ENC(PUmGIr24r0SPAYjnUJxduk4CuUYeNdxNatLOhO0dBGs=)
    password: ENC(5F8ZHm9E+nVLjTx6VTkFC9k8QG1sQei07zl/c+1tRxQ=)
    default-encoding: utf-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  datasource:
    url: jdbc:mysql://localhost:3306/test?characterEncoding=utf8&allowMultiQueries=true&useSSL=false&autoReconnect=true&serverTimezone=UTC
    username: ENC(I3s1vXxb/SOhh6kxQKrXkw==)
    password: ENC(M8WAdNQqguyqHMHc2Ei0Rg==)
    driver-class-name: com.mysql.cj.jdbc.Driver

#system
server:
  port: 8888
  tomcat:
    basedir: /data/layku/temp/
  servlet:
    session:
      timeout: 18000

#aliyun mail
aliyun:
  region-id: ENC(0kiREhAd5WNdXWhYyuRuM40dlPE7Z2ZA)
  access-key-id: ENC(RBLIDVRzrFTzA0ly6dz9hMneRf5e6ZMrGjyvQB9go0RyQzCpYbVLWQ==)
  secret: ENC(l/WsFlbRs8WoSjQfLKNlvT2+b2yrIQi+TIz1Ll54XoJqbjUGBLT+IQ==)
  mail:
    account-name: ENC(3U9PRiCGw/etHHV/8RMk2hgOg5UADxr4)
    from-alias: ENC(TUo9dONsdLlxFXCrI2KsfF//XT52ColZhmgk5rtDiT8=)

#baidu ip
baidu:
  ip:
    ak: ENC(o3JjaE4H2sJxSgd2/+4ZojptCOTztFltdoqN2U343EG/P5s8Z1f759SZWTF8F17i)
    sk: ENC(vA/3BpkX4RgLXtTlcGMDaCteuff+XNSVfpx8HccB4vMRFfmxl4IU1NpQe73Qiywp)

#修改
jasypt:
  encryptor:
    password: xxx